class Worker:
    def __init__(self, id: int, state: int) -> None: ...
    def perform_task(self) -> None: ...
    def report_state(self) -> int: ...

class Aggregator:
    def __init__(self) -> None: ...
    def collect_state(self, state: int) -> None: ...
    def get_all_states(self) -> list[int]: ...
